node_js: lts/*
language: node_js

definitions:
  - import-cert-win: &import-cert-win
    - |
      echo $WIN_CSC_LINK > cert.p12
      certutil -p $WIN_CSC_KEY_PASSWORD -importpfx ./cert.p12

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"

jobs:
  include:
    - stage: test
      name: Test on Linux
      script:
      - COVERAGE=1 npm run all -- --x64 --no-compress
      after_success: npx codecov
    - stage: test
      name: Test on Windows
      os: windows
      before_install: *import-cert-win
      script:
      - npm run all -- --x64 --no-compress
    - stage: "distro"
      name: "Build Linux distro"
      os: linux
      script:
      - npm run build -- --linux --publish
    - stage: "distro"
      name: "Build Windows distro"
      os: windows
      before_install: *import-cert-win
      script:
      - npm run build -- --win --publish
    - stage: "distro"
      name: "Build MacOS distro"
      os: osx
      osx_image: xcode11.2
      script:
      - npm run build -- --mac --publish
    - stage: "post distro"
      git:
        depth: false
      script:
      - npm run send-license-book-summary
stages:
  - name: test
    if: type != api OR env(SKIP_TESTS) != "true"
  - name: "distro"
    if: tag =~ ^v\d
  - name: "post distro"
    if: tag =~ ^v\d
